name: Deploy Travel-Easily

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Add deployment step here (to Heroku, Vercel, DockerHub, etc.)
      - name: Deployment step
        run: echo "Insert your deployment command here (e.g., Docker, SCP, rsync, etc.)"
